import { MasterFeatureItem } from "../types";

export const MASTER_FEATURES_INVENTORY: MasterFeatureItem[] = [
    // ==========================================
    // PART I — CONSUMER-FACING TRANSACTIONAL (44)
    // ==========================================
    // Sec. A — Cash-In / Top-Up Funding (6 items)
    {
        id: "A.1",
        sectionKey: "A",
        sectionTitle: "Cash-In / Top-Up Funding",
        part: "Part I — Consumer-Facing",
        title: "Bank Transfer Cash-In",
        description: "Links a bank account and pushes funds into the wallet via real-time InstaPay (instant, up to PHP 50,000) or batch-cleared PESONet (same-day, higher value) interbank rails.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "A.2",
        sectionKey: "A",
        sectionTitle: "Cash-In / Top-Up Funding",
        part: "Part I — Consumer-Facing",
        title: "Partner E-Wallet / International Remittance Cash-In",
        description: "Funds received from partner remittance networks or other wallets, including automated MTCN validation, beneficiary matching, and FX conversion for cross-border inflows.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },
    {
        id: "A.3",
        sectionKey: "A",
        sectionTitle: "Cash-In / Top-Up Funding",
        part: "Part I — Consumer-Facing",
        title: "Payroll / Bulk Disbursement Cash-In",
        description: "Employer or institution credits funds directly into employee wallets via an encrypted CSV/API batch process with real-time audit logging.",
        dashboards: ["Merchant", "User"],
        operatingSurfaceBadge: "Merchant + User",
        status: "Implemented",
    },
    {
        id: "A.4",
        sectionKey: "A",
        sectionTitle: "Cash-In / Top-Up Funding",
        part: "Part I — Consumer-Facing",
        title: "Virtual Account Number for Cash-In",
        description: "Dedicated bank account number issued per user so banks can push funds in by account number rather than mobile alias.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "A.5",
        sectionKey: "A",
        sectionTitle: "Cash-In / Top-Up Funding",
        part: "Part I — Consumer-Facing",
        title: "Government Social Subsidy Direct Cash-In",
        description: "Dedicated disbursement channel for government aid programs (e.g., cash transfer, pension) that matches national ID/phone registries for automated distribution.",
        dashboards: ["User", "Admin/Ops"],
        operatingSurfaceBadge: "User + Admin",
        status: "Compliant",
    },
    {
        id: "A.6",
        sectionKey: "A",
        sectionTitle: "Cash-In / Top-Up Funding",
        part: "Part I — Consumer-Facing",
        title: "Promotional Cashback / Voucher Purse",
        description: "Deposits campaign credits, merchant cashback, or redeemed vouchers into a segregated promotional purse with its own expiry timer.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },

    // Sec. B — Send, Pay, Transfer & Social Remittance (P2P) (6 items)
    {
        id: "B.1",
        sectionKey: "B",
        sectionTitle: "Send, Pay, Transfer & Social Remittance (P2P)",
        part: "Part I — Consumer-Facing",
        title: "Send Money (P2P)",
        description: "Instant wallet-to-wallet transfer to another user via mobile number, executing an atomic debit/credit on the internal ledger with sub-second balance reflection.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "B.2",
        sectionKey: "B",
        sectionTitle: "Send, Pay, Transfer & Social Remittance (P2P)",
        part: "Part I — Consumer-Facing",
        title: "Bank Transfer Out",
        description: "Sends funds from the wallet to an external bank account via the InstaPay or PESONet interbank rails.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "B.3",
        sectionKey: "B",
        sectionTitle: "Send, Pay, Transfer & Social Remittance (P2P)",
        part: "Part I — Consumer-Facing",
        title: "Cash Pick-Up / Padala Remittance",
        description: "Sends funds for cash pick-up at a partner branch rather than to an active wallet account.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },
    {
        id: "B.4",
        sectionKey: "B",
        sectionTitle: "Send, Pay, Transfer & Social Remittance (P2P)",
        part: "Part I — Consumer-Facing",
        title: "International Remittance Receive",
        description: "Accepts inbound remittances from partner international transfer networks with upfront foreign exchange rate settlement.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "B.5",
        sectionKey: "B",
        sectionTitle: "Send, Pay, Transfer & Social Remittance (P2P)",
        part: "Part I — Consumer-Facing",
        title: "Transaction Cancellation (Pre-Settlement)",
        description: "Cancels an authorized payment or scheduled transfer before final clearing and batch posting.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },
    {
        id: "B.6",
        sectionKey: "B",
        sectionTitle: "Send, Pay, Transfer & Social Remittance (P2P)",
        part: "Part I — Consumer-Facing",
        title: "Refund to Sender",
        description: "Returns funds to the original payer for a reversed or disputed transaction through the core refund processor.",
        dashboards: ["User", "Admin/Ops"],
        operatingSurfaceBadge: "User + Admin",
        status: "Implemented",
    },

    // Sec. C — QR Code Transactions (7 items)
    {
        id: "C.1",
        sectionKey: "C",
        sectionTitle: "QR Code Transactions",
        part: "Part I — Consumer-Facing",
        title: "Personal QR Generation",
        description: "User generates a static personal QR code to receive money instantly from another user.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },
    {
        id: "C.2",
        sectionKey: "C",
        sectionTitle: "QR Code Transactions",
        part: "Part I — Consumer-Facing",
        title: "Merchant QR Generation (Static)",
        description: "Merchant displays a fixed EMVCo/QR Ph-compliant QR code; customer scans it and manually enters the transaction amount.",
        dashboards: ["Merchant"],
        operatingSurfaceBadge: "Merchant Portal",
        status: "Active Rail",
    },
    {
        id: "C.3",
        sectionKey: "C",
        sectionTitle: "QR Code Transactions",
        part: "Part I — Consumer-Facing",
        title: "Merchant QR Generation (Dynamic)",
        description: "QR code generated per-transaction with the exact payable amount and reference token pre-encoded.",
        dashboards: ["Merchant"],
        operatingSurfaceBadge: "Merchant Portal",
        status: "Active Rail",
    },
    {
        id: "C.4",
        sectionKey: "C",
        sectionTitle: "QR Code Transactions",
        part: "Part I — Consumer-Facing",
        title: "Scan-to-Pay",
        description: "User scans a merchant or personal QR code via camera viewfinder to initiate an immediate debit payment.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "C.5",
        sectionKey: "C",
        sectionTitle: "QR Code Transactions",
        part: "Part I — Consumer-Facing",
        title: "Show-to-Pay / Reverse Scan",
        description: "User displays a dynamic one-time barcode/QR for a cashier scanner to capture, triggering an authenticated auto-debit.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },
    {
        id: "C.6",
        sectionKey: "C",
        sectionTitle: "QR Code Transactions",
        part: "Part I — Consumer-Facing",
        title: "QR Code Validation",
        description: "Confirms a scanned code is well-formed, cryptographic signature is verified, unexpired, and belongs to a valid counterparty.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },
    {
        id: "C.7",
        sectionKey: "C",
        sectionTitle: "QR Code Transactions",
        part: "Part I — Consumer-Facing",
        title: "Interoperable & Cross-Border QR Acceptance",
        description: "Merged national QR Ph interoperability (P2P & P2M cross-provider routing) and cross-border merchant scan integration (via regional switches/Alipay+) with real-time FX conversion.",
        dashboards: ["User", "Merchant"],
        operatingSurfaceBadge: "User + Merchant",
        status: "Active Rail",
    },

    // Sec. D — Merchant Checkout & Point-of-Sale (6 items)
    {
        id: "D.1",
        sectionKey: "D",
        sectionTitle: "Merchant Checkout & Point-of-Sale",
        part: "Part I — Consumer-Facing",
        title: "Pay / Merchant Checkout (In-Store)",
        description: "Pays a registered merchant for goods or services directly at the physical point of sale.",
        dashboards: ["User", "Merchant"],
        operatingSurfaceBadge: "User + Merchant",
        status: "Active Rail",
    },
    {
        id: "D.2",
        sectionKey: "D",
        sectionTitle: "Merchant Checkout & Point-of-Sale",
        part: "Part I — Consumer-Facing",
        title: "Online Checkout (Hosted / API Plugin)",
        description: "Wallet surfaces as a checkout method on partner web/mobile sites via hosted modal or plugin with OTP/biometric validation.",
        dashboards: ["User", "Merchant"],
        operatingSurfaceBadge: "User + Merchant",
        status: "Implemented",
    },
    {
        id: "D.3",
        sectionKey: "D",
        sectionTitle: "Merchant Checkout & Point-of-Sale",
        part: "Part I — Consumer-Facing",
        title: "Vaulted 1-Click Pay / Card-on-File",
        description: "Binds the wallet as a vaulted payment instrument on merchant accounts for automated, tokenized recurring debits.",
        dashboards: ["User", "Merchant"],
        operatingSurfaceBadge: "User + Merchant",
        status: "Implemented",
    },
    {
        id: "D.4",
        sectionKey: "D",
        sectionTitle: "Merchant Checkout & Point-of-Sale",
        part: "Part I — Consumer-Facing",
        title: "Tap-to-Pay / Contactless NFC",
        description: "Contactless in-store payment using Host Card Emulation (HCE) to tap a mobile device against EMV contactless POS terminals.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "D.5",
        sectionKey: "D",
        sectionTitle: "Merchant Checkout & Point-of-Sale",
        part: "Part I — Consumer-Facing",
        title: "Hybrid Smart Card Acceptance",
        description: "Accepts dual-interface cards (contact EMV chip + contactless antenna + fallback magnetic stripe) at hybrid POS terminals.",
        dashboards: ["User", "Merchant"],
        operatingSurfaceBadge: "User + Merchant",
        status: "Active Rail",
    },
    {
        id: "D.6",
        sectionKey: "D",
        sectionTitle: "Merchant Checkout & Point-of-Sale",
        part: "Part I — Consumer-Facing",
        title: "Magnetic Secure Transmission (MST) Emulation",
        description: "Transmits magnetic pulses mimicking stripe swipes for legacy point-of-sale terminals lacking contactless NFC capabilities.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },

    // Sec. E — Cash-Out & Outward Disbursement (3 items)
    {
        id: "E.1",
        sectionKey: "E",
        sectionTitle: "Cash-Out & Outward Disbursement",
        part: "Part I — Consumer-Facing",
        title: "Outward Instant Bank Transfer (InstaPay)",
        description: "Real-time outward fund transfer up to PHP 50,000 to any participating interbank destination with instant balance debit.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "E.2",
        sectionKey: "E",
        sectionTitle: "Cash-Out & Outward Disbursement",
        part: "Part I — Consumer-Facing",
        title: "Outward Batch Transfer (PESONet)",
        description: "High-value transfers clearing same-day through national automated clearing house processing windows.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "E.3",
        sectionKey: "E",
        sectionTitle: "Cash-Out & Outward Disbursement",
        part: "Part I — Consumer-Facing",
        title: "Settlement Net-Sweep Cash-Out",
        description: "Automated end-of-day net sweep of settled merchant funds into registered commercial bank accounts.",
        dashboards: ["Merchant", "Admin/Ops"],
        operatingSurfaceBadge: "Merchant + Admin",
        status: "Active Rail",
    },

    // Sec. F — Bills, Government & Utility/Telco Payments (4 items)
    {
        id: "F.1",
        sectionKey: "F",
        sectionTitle: "Bills, Government & Utility/Telco Payments",
        part: "Part I — Consumer-Facing",
        title: "Bills Payment (Utilities & Billers)",
        description: "Direct settlement of water, electricity, telco, and enterprise bills via integrated aggregators with real-time posting.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "F.2",
        sectionKey: "F",
        sectionTitle: "Bills, Government & Utility/Telco Payments",
        part: "Part I — Consumer-Facing",
        title: "Buy Load / eLoad",
        description: "Prepaid telecommunication airtime credits, data packages, and digital bundles purchased at wholesale-linked rates.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "F.3",
        sectionKey: "F",
        sectionTitle: "Bills, Government & Utility/Telco Payments",
        part: "Part I — Consumer-Facing",
        title: "Government Payments",
        description: "Settles statutory contributions, corporate taxes, and national permits using standardized Payment Reference Numbers (PRN).",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "F.4",
        sectionKey: "F",
        sectionTitle: "Bills, Government & Utility/Telco Payments",
        part: "Part I — Consumer-Facing",
        title: "Cryptographically Signed E-Receipt",
        description: "Generates tamper-evident digital receipts with verified cryptographic signatures meeting statutory electronic billing criteria.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },

    // Sec. G — Embedded Financial Services (2 items)
    {
        id: "G.1",
        sectionKey: "G",
        sectionTitle: "Embedded Financial Services",
        part: "Part I — Consumer-Facing",
        title: "Micro-Loan / Revolving Credit Line",
        description: "Short-term consumer credit lines disbursed to and repaid from the wallet, scored by historical wallet transaction velocity.",
        dashboards: ["User", "Admin/Ops"],
        operatingSurfaceBadge: "User + Admin",
        status: "Implemented",
    },
    {
        id: "G.2",
        sectionKey: "G",
        sectionTitle: "Embedded Financial Services",
        part: "Part I — Consumer-Facing",
        title: "Card Issuance (Dual-Interface & Virtual)",
        description: "Merged issuance suite: virtual card tokens for online spending and physical dual-interface smart cards (contact EMV chip + contactless NFC applet + fallback magnetic stripe) funded from wallet balance.",
        dashboards: ["User", "Admin/Ops"],
        operatingSurfaceBadge: "User + Admin",
        status: "Active Rail",
    },

    // Sec. H — Account, Security & Self-Service Support (10 items)
    {
        id: "H.1",
        sectionKey: "H",
        sectionTitle: "Account, Security & Self-Service Support",
        part: "Part I — Consumer-Facing",
        title: "Account Registration & Onboarding",
        description: "Initial user registration capturing mobile MSISDN, basic demographic profile, and terms consent.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },
    {
        id: "H.2",
        sectionKey: "H",
        sectionTitle: "Account, Security & Self-Service Support",
        part: "Part I — Consumer-Facing",
        title: "KYC Tier Upgrade",
        description: "Submission of government ID and live selfie biometric captures to unlock higher regulatory transaction and balance tiers.",
        dashboards: ["User", "Admin/Ops"],
        operatingSurfaceBadge: "User + Admin",
        status: "Compliant",
    },
    {
        id: "H.3",
        sectionKey: "H",
        sectionTitle: "Account, Security & Self-Service Support",
        part: "Part I — Consumer-Facing",
        title: "Balance & Transaction History",
        description: "Real-time ledger balance display and searchable historical statement of settled, pending, and reversed transactions.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Active Rail",
    },
    {
        id: "H.4",
        sectionKey: "H",
        sectionTitle: "Account, Security & Self-Service Support",
        part: "Part I — Consumer-Facing",
        title: "Transaction Limits Management",
        description: "Configurable dashboard displaying current daily, monthly, and per-transaction spending caps based on KYC tiering.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Compliant",
    },
    {
        id: "H.5",
        sectionKey: "H",
        sectionTitle: "Account, Security & Self-Service Support",
        part: "Part I — Consumer-Facing",
        title: "Biometric 2 Factor Authentication",
        description: "Hardware-backed biometric verification (fingerprint / FaceID) paired with device cryptographic keys as mandatory two-factor authorization for high-value debits.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Compliant",
    },
    {
        id: "H.6",
        sectionKey: "H",
        sectionTitle: "Account, Security & Self-Service Support",
        part: "Part I — Consumer-Facing",
        title: "One-Time Password (OTP) Verification",
        description: "Secondary verification code delivered via secure out-of-band channels for critical profile alterations.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Compliant",
    },
    {
        id: "H.7",
        sectionKey: "H",
        sectionTitle: "Account, Security & Self-Service Support",
        part: "Part I — Consumer-Facing",
        title: "Card / Account Linking & Management",
        description: "Adds, removes, verifies, or sets default funding sources across external bank accounts and debit cards.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },
    {
        id: "H.8",
        sectionKey: "H",
        sectionTitle: "Account, Security & Self-Service Support",
        part: "Part I — Consumer-Facing",
        title: "Dispute / Chargeback Filing",
        description: "In-app customer ticketing interface to dispute fraudulent, erroneous, or duplicate merchant transactions.",
        dashboards: ["User", "Admin/Ops"],
        operatingSurfaceBadge: "User + Admin",
        status: "Implemented",
    },
    {
        id: "H.9",
        sectionKey: "H",
        sectionTitle: "Account, Security & Self-Service Support",
        part: "Part I — Consumer-Facing",
        title: "Account Freeze / Lock",
        description: "Immediate self-service or support-assisted kill switch to lock wallet operations upon suspected device compromise.",
        dashboards: ["User", "Admin/Ops"],
        operatingSurfaceBadge: "User + Admin",
        status: "Compliant",
    },
    {
        id: "H.10",
        sectionKey: "H",
        sectionTitle: "Account, Security & Self-Service Support",
        part: "Part I — Consumer-Facing",
        title: "Customer Support / Help Center",
        description: "Integrated ticketing, live agent chat, and contextual knowledge base for transactional query resolution.",
        dashboards: ["User", "Admin/Ops"],
        operatingSurfaceBadge: "User + Admin",
        status: "Implemented",
    },

    // Sec. I — Additional Consumer & Household Features (3 items)
    {
        id: "I.1",
        sectionKey: "I",
        sectionTitle: "Additional Consumer & Household Features",
        part: "Part I — Consumer-Facing",
        title: "Voucher / Promo Code Redemption",
        description: "Validates and applies merchant discount codes or campaign vouchers directly into checkout sessions.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },
    {
        id: "I.2",
        sectionKey: "I",
        sectionTitle: "Additional Consumer & Household Features",
        part: "Part I — Consumer-Facing",
        title: "Spending Insights / Budgeting Dashboard",
        description: "Categorized analytics module tracking expenditure patterns across bills, groceries, leisure, and transfers.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },
    {
        id: "I.3",
        sectionKey: "I",
        sectionTitle: "Additional Consumer & Household Features",
        part: "Part I — Consumer-Facing",
        title: "Saved Billers & Favorites",
        description: "Stores validated biller reference tokens, frequent bank accounts, and contact aliases for streamlined re-payment.",
        dashboards: ["User"],
        operatingSurfaceBadge: "User App",
        status: "Implemented",
    },

    // ==========================================
    // PART II — MERCHANT & DEVELOPER PLATFORM (8)
    // ==========================================
    // Sec. J — Merchant Platform & Developer Enablement (8 items)
    {
        id: "J.1",
        sectionKey: "J",
        sectionTitle: "Merchant Platform & Developer Enablement",
        part: "Part II — Merchant & Developer",
        title: "Merchant Onboarding & Underwriting (KYB)",
        description: "Automated ingestion of corporate registration documents, tax IDs, and beneficial ownership verification for acquiring compliance.",
        dashboards: ["Merchant", "Admin/Ops"],
        operatingSurfaceBadge: "Merchant + Admin",
        status: "Compliant",
    },
    {
        id: "J.2",
        sectionKey: "J",
        sectionTitle: "Merchant Platform & Developer Enablement",
        part: "Part II — Merchant & Developer",
        title: "Merchant Business Dashboard & RBAC",
        description: "Consolidated sales analytics and settlement portal featuring strict Role-Based Access Control (cashier, accountant, administrator).",
        dashboards: ["Merchant"],
        operatingSurfaceBadge: "Merchant Portal",
        status: "Compliant",
    },
    {
        id: "J.3",
        sectionKey: "J",
        sectionTitle: "Merchant Platform & Developer Enablement",
        part: "Part II — Merchant & Developer",
        title: "Dynamic Payment Link & Invoice Generator",
        description: "Web interface enabling merchants to generate itemized checkout links dispatchable via messaging or email.",
        dashboards: ["Merchant"],
        operatingSurfaceBadge: "Merchant Portal",
        status: "Active Rail",
    },
    {
        id: "J.4",
        sectionKey: "J",
        sectionTitle: "Merchant Platform & Developer Enablement",
        part: "Part II — Merchant & Developer",
        title: "POS Terminal Fleet & Remote Management",
        description: "Centralized device management console managing Over-the-Air (OTA) firmware, security patches, and remote terminal revocation.",
        dashboards: ["Merchant", "Admin/Ops"],
        operatingSurfaceBadge: "Merchant + Admin",
        status: "Active Rail",
    },
    {
        id: "J.5",
        sectionKey: "J",
        sectionTitle: "Merchant Platform & Developer Enablement",
        part: "Part II — Merchant & Developer",
        title: "Real-Time Cashier Notification Engine",
        description: "Low-latency websocket bridge pushing instant audio/visual payment approvals onto cashier POS registers.",
        dashboards: ["Merchant"],
        operatingSurfaceBadge: "Merchant Portal",
        status: "Active Rail",
    },
    {
        id: "J.6",
        sectionKey: "J",
        sectionTitle: "Merchant Platform & Developer Enablement",
        part: "Part II — Merchant & Developer",
        title: "Merchant API / SDK & Webhook Dispatch",
        description: "Developer sandbox, SDK libraries, and automated event dispatchers pushing cryptographically signed event notifications.",
        dashboards: ["Merchant"],
        operatingSurfaceBadge: "Merchant Portal",
        status: "Implemented",
    },
    {
        id: "J.7",
        sectionKey: "J",
        sectionTitle: "Merchant Platform & Developer Enablement",
        part: "Part II — Merchant & Developer",
        title: "Hybrid POS Terminal Certification & Kernel",
        description: "EMV Level 1 and Level 2 contact/contactless kernel provisioning for smart POS terminals with configured fallback logic.",
        dashboards: ["Admin/Ops", "Merchant"],
        operatingSurfaceBadge: "Admin + Merchant",
        status: "Compliant",
    },
    {
        id: "J.8",
        sectionKey: "J",
        sectionTitle: "Merchant Platform & Developer Enablement",
        part: "Part II — Merchant & Developer",
        title: "Bulk Disbursement / Payroll Payout",
        description: "Enterprise batch disbursement engine supporting scheduled payroll runs, multi-vendor commission splits, and supplier payouts.",
        dashboards: ["Merchant"],
        operatingSurfaceBadge: "Merchant Portal",
        status: "Active Rail",
    },

    // ==========================================
    // PART III — BACKEND ARCHITECTURE & PROCESSING (32)
    // ==========================================
    // Sec. K — Core Transaction Processing & Ledger Engine (11 items)
    {
        id: "K.1",
        sectionKey: "K",
        sectionTitle: "Core Transaction Processing & Ledger Engine",
        part: "Part III — Backend & Processing",
        title: "Transaction Authorization (Hold & Capture)",
        description: "Two-phase balance validation and reservation system preventing overdrafts and race conditions during in-flight payments.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },
    {
        id: "K.2",
        sectionKey: "K",
        sectionTitle: "Core Transaction Processing & Ledger Engine",
        part: "Part III — Backend & Processing",
        title: "Double-Entry Ledger Posting",
        description: "Immutable financial ledger executing atomic debit and credit entries across liability, asset, fee, and settlement accounts.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },
    {
        id: "K.3",
        sectionKey: "K",
        sectionTitle: "Core Transaction Processing & Ledger Engine",
        part: "Part III — Backend & Processing",
        title: "Real-Time Balance Update",
        description: "Event-driven balance projection updating client cache and socket feeds within sub-second latencies.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Active Rail",
    },
    {
        id: "K.4",
        sectionKey: "K",
        sectionTitle: "Core Transaction Processing & Ledger Engine",
        part: "Part III — Backend & Processing",
        title: "Idempotency / Duplicate Handling",
        description: "Distributed cache locking on unique client idempotency keys, guaranteeing exactly-once transaction execution.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },
    {
        id: "K.5",
        sectionKey: "K",
        sectionTitle: "Core Transaction Processing & Ledger Engine",
        part: "Part III — Backend & Processing",
        title: "QR Code Generation & Signing Engine",
        description: "Cryptographic signing service generating secure EMVCo-compliant QR payloads embedding digital integrity signatures.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },
    {
        id: "K.6",
        sectionKey: "K",
        sectionTitle: "Core Transaction Processing & Ledger Engine",
        part: "Part III — Backend & Processing",
        title: "Fee & Surcharge Calculation Engine",
        description: "Dynamic fee evaluation engine computing interchange, gateway convenience fees, and merchant discount rates prior to ledger post.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Active Rail",
    },
    {
        id: "K.7",
        sectionKey: "K",
        sectionTitle: "Core Transaction Processing & Ledger Engine",
        part: "Part III — Backend & Processing",
        title: "Notification Dispatch Service",
        description: "Multi-channel routing pipeline delivering SMS, push notifications, and email transaction receipts.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Active Rail",
    },
    {
        id: "K.8",
        sectionKey: "K",
        sectionTitle: "Core Transaction Processing & Ledger Engine",
        part: "Part III — Backend & Processing",
        title: "Retry, Compensation & Saga Orchestration",
        description: "Distributed transaction coordinator executing backward-recovery compensating actions upon upstream microservice timeout.",
        dashboards: ["System", "Admin/Ops"],
        operatingSurfaceBadge: "System + Admin",
        status: "Compliant",
    },
    {
        id: "K.9",
        sectionKey: "K",
        sectionTitle: "Core Transaction Processing & Ledger Engine",
        part: "Part III — Backend & Processing",
        title: "Offline / Batch Transaction Queueing",
        description: "Persistent transactional queue isolating and replaying offline store-and-forward authorizations upon network recovery.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Active Rail",
    },
    {
        id: "K.10",
        sectionKey: "K",
        sectionTitle: "Core Transaction Processing & Ledger Engine",
        part: "Part III — Backend & Processing",
        title: "Card Network Integration (Issuing / Acquiring)",
        description: "Direct ISO-8583 and ISO-20022 gateway connectors linking virtual/physical cards to international payment networks.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },
    {
        id: "K.11",
        sectionKey: "K",
        sectionTitle: "Core Transaction Processing & Ledger Engine",
        part: "Part III — Backend & Processing",
        title: "MDR & Fee Configuration Engine",
        description: "Tiered fee management matrix permitting custom merchant discount schedules by volume, category, or processing rail.",
        dashboards: ["Admin/Ops", "Merchant"],
        operatingSurfaceBadge: "Admin + Merchant",
        status: "Implemented",
    },

    // Sec. L — Settlement, Clearing & Reconciliation (6 items)
    {
        id: "L.1",
        sectionKey: "L",
        sectionTitle: "Settlement, Clearing & Reconciliation",
        part: "Part III — Backend & Processing",
        title: "Interbank Switching (InstaPay / PESONet)",
        description: "Bilateral gateway interface routing real-time and clearing-house batch settlements to national banking switches.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Active Rail",
    },
    {
        id: "L.2",
        sectionKey: "L",
        sectionTitle: "Settlement, Clearing & Reconciliation",
        part: "Part III — Backend & Processing",
        title: "Merchant Settlement & Disbursement",
        description: "Automated batch net-settlement engine consolidating daily sales less fees into merchant registered depository accounts.",
        dashboards: ["Admin/Ops", "Merchant"],
        operatingSurfaceBadge: "Admin + Merchant",
        status: "Active Rail",
    },
    {
        id: "L.3",
        sectionKey: "L",
        sectionTitle: "Settlement, Clearing & Reconciliation",
        part: "Part III — Backend & Processing",
        title: "Daily / Three-Way Reconciliation",
        description: "Automated ledger-to-bank-to-network reconciliation pipeline identifying and flagging settlement discrepancies.",
        dashboards: ["Admin/Ops"],
        operatingSurfaceBadge: "Admin Console",
        status: "Compliant",
    },
    {
        id: "L.4",
        sectionKey: "L",
        sectionTitle: "Settlement, Clearing & Reconciliation",
        part: "Part III — Backend & Processing",
        title: "Chargeback & Dispute Processing",
        description: "Back-office arbitration console managing evidence submission, representation cycles, and reserve account adjustments.",
        dashboards: ["Admin/Ops", "Merchant"],
        operatingSurfaceBadge: "Admin + Merchant",
        status: "Implemented",
    },
    {
        id: "L.5",
        sectionKey: "L",
        sectionTitle: "Settlement, Clearing & Reconciliation",
        part: "Part III — Backend & Processing",
        title: "Automated Refund Reversal Processor",
        description: "Programmatic refund pipeline unwinding payment legs, reversing fee allocations, and re-crediting customer balances.",
        dashboards: ["System", "User"],
        operatingSurfaceBadge: "System + User",
        status: "Active Rail",
    },
    {
        id: "L.6",
        sectionKey: "L",
        sectionTitle: "Settlement, Clearing & Reconciliation",
        part: "Part III — Backend & Processing",
        title: "Negative-Balance Recovery & Clawback",
        description: "Automated recovery engine creating ledger liability liens and auto-deducting balances upon subsequent user cash-in.",
        dashboards: ["Admin/Ops", "User"],
        operatingSurfaceBadge: "Admin + User",
        status: "Compliant",
    },

    // Sec. M — Risk, Fraud, AML/CFT & Security (15 items)
    {
        id: "M.1",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "AML Transaction Monitoring",
        description: "Heuristic and rules-based screening detecting smurfing, layering, and covered transaction threshold violations.",
        dashboards: ["Admin/Ops"],
        operatingSurfaceBadge: "Admin Console",
        status: "Compliant",
    },
    {
        id: "M.2",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Velocity / Rate Limiting & Tier Caps",
        description: "Automated rate-limiting framework enforcing internal per-minute call limits, daily outflow caps, and KYC tier ceilings.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },
    {
        id: "M.3",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Encryption & Tokenization",
        description: "PCI-DSS compliant hardware/software tokenization isolating PANs, sensitive payment secrets, and user PII.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },
    {
        id: "M.4",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Session & Token Management",
        description: "Issues and validates short-lived access JWT tokens, cryptographic refresh tokens, and device-bound sessions.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },
    {
        id: "M.5",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Immutable Audit Logging",
        description: "Append-only, cryptographically chained audit log tracking all state mutations and administrative console actions.",
        dashboards: ["System", "Admin/Ops"],
        operatingSurfaceBadge: "System + Admin",
        status: "Compliant",
    },
    {
        id: "M.6",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Regulatory & Statutory Reporting",
        description: "Automated reporting pipeline compiling mandatory central bank liquidity statements and suspicious activity reports.",
        dashboards: ["Admin/Ops"],
        operatingSurfaceBadge: "Admin Console",
        status: "Compliant",
    },
    {
        id: "M.7",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Device Fingerprinting & Binding",
        description: "Extracts unique hardware identifiers to enforce 1-to-1 trusted device binding and flag unauthorized session hijacks.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },
    {
        id: "M.8",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Adaptive / Step-Up Authentication",
        description: "Dynamic risk scoring requiring secondary biometric or OTP challenges upon high-risk transaction detection.",
        dashboards: ["System", "User"],
        operatingSurfaceBadge: "System + User",
        status: "Compliant",
    },
    {
        id: "M.9",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Sanctions & Watchlist Screening",
        description: "Real-time screening of counterparties against OFAC, PEP, and local central bank enforcement registries.",
        dashboards: ["System", "Admin/Ops"],
        operatingSurfaceBadge: "System + Admin",
        status: "Compliant",
    },
    {
        id: "M.10",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Data Privacy & Retention Management",
        description: "Enforces statutory data retention limits and cryptographic data redaction under local privacy acts.",
        dashboards: ["Admin/Ops"],
        operatingSurfaceBadge: "Admin Console",
        status: "Compliant",
    },
    {
        id: "M.11",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Analytics & Data Warehouse Pipeline",
        description: "Near-real-time CDC ETL pipeline streaming transactional telemetry into data warehouses for BI analysis.",
        dashboards: ["Admin/Ops"],
        operatingSurfaceBadge: "Admin Console",
        status: "Active Rail",
    },
    {
        id: "M.12",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Fraud-Model Monitoring & Retraining",
        description: "MLOps pipeline monitoring inference drift and periodically retraining anomaly detection algorithms.",
        dashboards: ["Admin/Ops"],
        operatingSurfaceBadge: "Admin Console",
        status: "Compliant",
    },
    {
        id: "M.13",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Encryption Key Management (HSM)",
        description: "FIPS 140-2 Level 3 Hardware Security Modules generating, rotating, and managing master zone and PIN encryption keys.",
        dashboards: ["Admin/Ops"],
        operatingSurfaceBadge: "Admin Console",
        status: "Compliant",
    },
    {
        id: "M.14",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "Transport Encryption in Transit",
        description: "Enforces TLS 1.3 with forward secrecy, strict mTLS for inter-service communication, and certificate pinning.",
        dashboards: ["System"],
        operatingSurfaceBadge: "System Engine",
        status: "Compliant",
    },
    {
        id: "M.15",
        sectionKey: "M",
        sectionTitle: "Risk, Fraud, AML/CFT & Security",
        part: "Part III — Backend & Processing",
        title: "EMV Fallback Fraud Monitoring",
        description: "Monitors and subjects magstripe fallback transactions to enhanced anomaly heuristics, mitigating liability shift risks.",
        dashboards: ["Admin/Ops"],
        operatingSurfaceBadge: "Admin Console",
        status: "Compliant",
    },
];

export const SECTION_METADATA: Record<string, { title: string; count: number; part: string }> = {
    A: { title: "Cash-In / Top-Up Funding", count: 6, part: "Part I" },
    B: { title: "Send, Pay, Transfer & Social Remittance (P2P)", count: 6, part: "Part I" },
    C: { title: "QR Code Transactions", count: 7, part: "Part I" },
    D: { title: "Merchant Checkout & Point-of-Sale", count: 6, part: "Part I" },
    E: { title: "Cash-Out & Outward Disbursement", count: 3, part: "Part I" },
    F: { title: "Bills, Government & Utility/Telco Payments", count: 4, part: "Part I" },
    G: { title: "Embedded Financial Services", count: 2, part: "Part I" },
    H: { title: "Account, Security & Self-Service Support", count: 10, part: "Part I" },
    I: { title: "Additional Consumer & Household Features", count: 3, part: "Part I" },
    J: { title: "Merchant Platform & Developer Enablement", count: 8, part: "Part II" },
    K: { title: "Core Transaction Processing & Ledger Engine", count: 11, part: "Part III" },
    L: { title: "Settlement, Clearing & Reconciliation", count: 6, part: "Part III" },
    M: { title: "Risk, Fraud, AML/CFT & Security", count: 15, part: "Part III" },
};
